### ISSUE TITLE
implement user registration

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/crm#1]
As a user, I want to be able to register in the VilnaCRM.

[Design](https://www.figma.com/file/hubQLvQkAlz8wWs2C60T3p/VilnaCRM?type=design&node-id=0-1&t=KiZ8Iq6wInNqRgPb-0)

[User flow](https://miro.com/app/board/uXjVPQ3J5kI=/)

[Architecture](https://miro.com/app/board/uXjVMG64hTs=/?share_link_id=932504055466)

### Technical requirements

- [ ] React
- [ ] Redux
- [ ] GraphQL
- [ ] MUI
- [ ] MSW
- [ ] Cypress
- [ ] Jest
- [ ] VilnaCRM UI library
- [ ] Storybook
- [ ] React Admin
- [ ] Sentry

### Tasks

- [ ] Make email design (@kravalg)
- [ ] Implement email for registration regarding the design
- [x] Design architecture for C4 model
- [ ] Implement a page for user registration regarding the design
- [ ] Implement a page for confirming user email
- [ ] Implement [admin panel](https://api-platform.com/docs/admin/) with user CRUD
- [ ] Add logging to the Sentry
- [ ] Write the issue comments with the website link and admin panel
- [ ] Cover code by autotests

### Acceptance criteria

- [ ] User can be registered regarding the design
- [ ] CRUD for user works in the admin panel
- [ ] User can confirm email regarding the design
- [ ] Issue comments exist with the website link and admin panel
- [ ] All tests passed
