### ISSUE TITLE
implement user registration

### ISSUE THREAD

**Issue by TuranC** [VilnaCRM-Org/crm#4]
# User Registration Feature

## Overview
As a customer, I want to be able to register on the VilnaCRM so that I can access its features.

[Design](https://www.figma.com/design/cbyqPMtiPNJGIIQH9eKZ9Y/VilnaCRM?node-id=0-1)

[User flow](https://miro.com/app/board/uXjVPQ3J5kI=/?share_link_id=531477366176)

[Architecture](https://miro.com/app/board/uXjVMG64hTs=/?share_link_id=496145003591)

## Technical Requirements
- [x] **React**: [React](https://reactjs.org/)
- [x] **TypeScript**: [TypeScript](https://www.typescriptlang.org/)
- [x] **MUI**: [MUI](https://mui.com/)
- [ ] **Jest**: [Jest](https://jestjs.io/ru/)
- [ ] **React Testing Library**: [React Testing Library](https://testing-library.com/docs/react-testing-library/intro)
- [ ] **Storybook**: [Storybook](https://storybook.js.org/)
- [ ] **Appolo GraphQL**: [Appolo GraphQL](https://www.apollographql.com/)
- [ ] **Memlab**: [Memlab](https://facebook.github.io/memlab/)
- [x] **Booletproof-react**: [Booletproof-react](https://github.com/alan2207/bulletproof-react)
- [x] **Eslint**: [Eslint](https://eslint.org/)
- [x] **Prettier**: [Prettier](https://prettier.io/)
- [x] **Husky**: [Husky](https://typicode.github.io/husky/)
- [x] **DI**: [DI](https://github.com/microsoft/tsyringe)
- [ ] **Playwright**: [Playwright](https://playwright.dev/)

## Tasks
- [x] Ensure usage of Node.js version 20.0.0 or higher.
- [ ] Update all obsolete package dependencies.
- [ ] Implement a sticky menu with responsive design support.
- [ ] Use i18n for text localization (e.g., `t('text_1')`).
- [ ] Implement the header according to design.
- [ ] Implement registration block:
  - Add registration form with validation for initial data, password, and email.
- [ ] Implement the footer with social media icons and email links
- [ ] Add end-to-end tests
- [ ] Add unit tests
- [ ] add documentation for this feature
- [ ] add footer to UI-kit
- [ ] fix absolute path
- [ ] Create a universal icon component that is able to load automatically SVG icons
- [ ] add CI action for generating documentation with chatGPT https://developers.codegpt.co/ *
- [ ] need to fix eslint errors in the project for import (@features/*/*) https://eslint.org/docs/latest/rules/no-restricted-imports
- [ ] in imports need update eslint rules for .txs and other type files
- [ ] visual tests with playwright
- [ ] add new command for install all dependencies and install git-hooks (husky)
- [ ] add eslint rooles for @/pathToFeature and for ../path inside feature (https://medium.com/thefork/escaping-relative-import-paths-hell-in-javascript-9f258baeb15e)
- [ ] add config for git, all files must be in LF and when push it, all files must be LF
- [ ] add new CI check [pnpm audit](https://pnpm.io/cli/audit)
- [ ] add [vite](https://vitejs.dev/) *
- [ ] add [vitest](https://vitest.dev/) *
- [ ] add [structurizr](https://structurizr.com/)
- [ ] add [Stryker-mutator](https://stryker-mutator.io/docs/stryker-js/typescript-checker/)
- [ ] need to add new CI action which will be responsible for merge automatically main branch in feature branch, if will be merge conflicts, CI action will be failed *

* Optional for probation period

## Acceptance Criteria
- [ ] Pixel-perfect implementation.
- [ ] Fully responsive design.
- [ ] Self-review conducted.
- [ ] Register button works as expected.
- [ ] Registration form and menu functioning correctly in mobile view.
- [ ] All Continuous Integration checks passing.
